### ISSUE TITLE
Initial packages

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#6]
Each of these will be tracked in separate PRs, but here's the place where we get to argue over the mandatory set of components (for initial release).

- [ ] prometheus stack (grafana, node-exporter, etc) (#11, #12)
- [ ] service catalog and relevant broker(s)
- [ ] k8s dashboard/heapster where missing (#15)
- [ ] An ingress controller (nginx? contour? traefik?)
- [ ] Logs sink (fluentd target, broker, and elasticsearch/whatever) (#13)
- [ ] TLS solution (cert-manager) (#14)
- [ ] minikube http/tls solution (pagekite/ngrok)
- [ ] A mariadb broker?

**Comment by arapulido** [comment]
Closing, as this is now fixed
